# Generated by Django 3.1.5 on 2021-01-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210124_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phonenumber',
        ),
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
